[build]
  command = "npm run build"
  publish = "build/client"

# [functions]
#   directory = "build/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/react-router-server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *; report-uri /csp-report"
